id: uipath_data_manager
learningObjectives:
  - Use the Data Manager to handle data and create variables.
hints:
  - Visit [Managing the Data in a
    Project](https://docs.uipath.com/studio-web/automation-cloud/latest/user-guide/managing-the-data-in-a-project)
    for detailed instructions.
  - The Data Manager is typically on the right panel within UiPath Studio.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Here's where the magic happens. Time to crack open the Data Manager.
          - text: Managing data is crucial—just imagine a library without a catalog. Same
              chaos, different setting.
          - text: Use the Data Manager in UiPath Studio to start organizing project data.
              Create variables that you can use throughout your project. This is
              your chance to be a data DJ—track on, track off.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
