id: uipath_setvariable_value
learningObjectives:
  - Create a flow to fill data into your variable
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that we've created our incredible variable, let's fill some data into it by creating a new step after our trigger
          - text: Click on the plus sign and search for `Set variable` and click on it
          - text: Now that you have an action inplace, choose the variable that we've created from the dropdown.
          - text: We'll choose data from the manual trigger called `Job Data`, expand the object and choose Robot name
    - actionId: bot_message
      params:
        person: lucca
        messages: 
          - text: Now its time to test your work :instruction[Click test from top left corner] and see it in action.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Fantastic work! You've dived into the world of automation with UiPath and
                mastered the essentials of data management. With your newfound
                skills, you're ready to tackle even bigger projects and impress
                Ness with your automation prowess. Go automate the world!
      - actionId: finish_step
